# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd08c274220c2b407ef89227cb2b51fba4a6c125700505765d95af620391d98194fce294e810d467ccc6a66663dfe149d79582dd868c36e80892323c68ef1fa2

test:
  secret_key_base: d9655b183816b0b83c6ec9a55e7d6527d486febf21e6294a158b172ce733bd78367c541404e0cb94be96e2b67ea59cd8209c2c9dbd1e01b5fe8b70435872750b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
