# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2514a15179e3f839663c35eb439e82c88d836554a8ec8c88244d06bbe84cf356d4380c4daef4545f68e01ed31e27d331c9c812ec80c04cd18effc96f0b097ec

test:
  secret_key_base: d0f83e5d77a63a0e05a52c174d942058a5d5634c01dcfe52cd50f83783a24fcda441f4e348afa6241f2b44a55f68ad9632ebd3236a7d6183a075d0ea7bca4916

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
