# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='friendships',
            name='friend1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Make_Friends.Person'),
        ),
        migrations.AddField(
            model_name='friendships',
            name='friend2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='Make_Friends.Person'),
        ),
    ]
